#!/usr/bin/env python3
"""Builder worker: turns queued SD card builder jobs into images.

Runs as root (loop devices and mounts) as the pimac-builder systemd
service. Claims one job at a time from the shared SQLite queue, writes
the user's mac.txt, invokes assemble-image.sh and relays its PROGRESS
lines into the job row so the status page can show them.

  worker.py            run the queue loop (the systemd service)
  worker.py --cleanup  one cleanup pass (expired builds, stale scratch)
"""

import json
import os
import shutil
import subprocess
import sys
import time

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "app"))
import db

ASSEMBLE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "assemble-image.sh")
CACHE_DIR = os.path.join(db.SCRATCH_DIR, "base-cache")
BUILD_TTL_SECONDS = 24 * 3600
POLL_SECONDS = 2
CLEANUP_INTERVAL_SECONDS = 600

MAC_TXT_TEMPLATE = """# ===================================================================
#  RPi-Mac configuration
#
#  Generated by the SD card builder. Edit this file from any computer,
#  then put the SD card back in the Pi and power on. Changes are
#  applied during boot.
# ===================================================================

# --- WiFi -----------------------------------------------------------
WIFI_SSID={wifi_ssid}
WIFI_PASS={wifi_pass}

# Two-letter regulatory country code (US, GB, DE, ...)
WIFI_COUNTRY={wifi_country}

# --- Display --------------------------------------------------------
# DISPLAY=hdmi   Standard HDMI output
# DISPLAY=dpi28  Waveshare 2.8inch DPI LCD (480x640 panel)
DISPLAY={display}

# Screen rotation in degrees: 0, 90, 180 or 270.
# Leave blank for automatic (270 on the DPI LCD, 0 on HDMI).
ROTATE={rotate}

# --- Access ----------------------------------------------------------
# SSH remote login (user: mac / password: rpimac). Set SSH=0 to disable.
SSH=1

# Password for the web interface. Blank = no password (default).
WEBUI_PASS=

# --- Debugging ------------------------------------------------------
# Set DEBUG=1 to show the Linux boot console instead of the Mac splash.
DEBUG=0

# --- Recovery notes (no need to edit) --------------------------------
# * If the device fails to finish booting 3 times in a row, it switches
#   to a verbose boot automatically so errors are visible on screen
#   (bootcount.txt next to this file tracks the attempts).
# * If the emulator itself keeps crashing, a login console appears on
#   the display with diagnostics (user: mac / password: rpimac).
# * SSH (if enabled) is at mac@<this Pi's IP> or rpimac.local.
# * If the Pi can't reach any WiFi a few minutes after boot, it opens
#   an access point called "RPi-Mac Setup" - join it and browse to
#   http://10.42.0.1/ to configure WiFi or use the Mac remotely.
"""


def log(message):
    print("[worker] %s" % message, flush=True)


def build_command(job, params, work_dir, out_file, mac_txt_path, conn):
    command = [
        "bash", ASSEMBLE,
        "--base", os.path.join(db.RELEASES_DIR, params["base"]),
        "--cache", CACHE_DIR,
        "--work", work_dir,
        "--out", out_file,
        "--mac-txt", mac_txt_path,
        "--boot", params["boot"],
    ]
    rom = db.get_component(conn, params["rom"])
    command += ["--rom", db.component_path(rom)]
    for comp_id in params["disks"]:
        comp = db.get_component(conn, comp_id)
        command += ["--disk", db.component_path(comp)]
    for blank in params["blank_disks"]:
        command += ["--blank", "%s:%d" % (blank["name"], blank["size_mb"])]
    for comp_id in params["isos"]:
        comp = db.get_component(conn, comp_id)
        command += ["--iso", db.component_path(comp)]
    return command


def run_job(conn, job):
    job_id = job["id"]
    params = json.loads(job["params"])
    log("starting job %s" % job_id)

    work_dir = os.path.join(db.SCRATCH_DIR, "job-" + job_id)
    build_dir = os.path.join(db.BUILDS_DIR, job_id)
    output_name = "RPi-Mac-%s.img.xz" % job_id
    out_file = os.path.join(build_dir, output_name)
    os.makedirs(work_dir, exist_ok=True)
    os.makedirs(build_dir, exist_ok=True)

    network = params["network"]
    mac_txt_path = os.path.join(work_dir, "mac.txt")
    with open(mac_txt_path, "w") as handle:
        handle.write(MAC_TXT_TEMPLATE.format(
            wifi_ssid=network["wifi_ssid"],
            wifi_pass=network["wifi_pass"],
            wifi_country=network["wifi_country"],
            display=params["display"],
            rotate=params["rotate"],
        ))

    command = build_command(job, params, work_dir, out_file, mac_txt_path, conn)
    log_lines = []
    try:
        process = subprocess.Popen(
            command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True)
        for line in process.stdout:
            line = line.rstrip("\n")
            log_lines.append(line)
            if len(log_lines) > 400:
                log_lines.pop(0)
            if line.startswith("PROGRESS "):
                parts = line.split(" ", 2)
                try:
                    percent = int(parts[1])
                except ValueError:
                    continue
                stage = ""
                if len(parts) > 2:
                    stage = parts[2]
                db.update_job(conn, job_id, percent=percent, stage=stage)
        process.wait()
        if process.returncode != 0:
            raise RuntimeError(
                "assemble-image.sh exited with %d" % process.returncode)
        os.chmod(out_file, 0o644)
        os.chmod(build_dir, 0o755)
        now = int(time.time())
        db.update_job(
            conn, job_id,
            status="done", stage="Done", percent=100,
            output_name=output_name,
            output_size=os.path.getsize(out_file),
            finished_at=now, expires_at=now + BUILD_TTL_SECONDS)
        log("job %s done" % job_id)
    except Exception as exc:
        tail = "\n".join(log_lines[-12:])
        log("job %s failed: %s\n%s" % (job_id, exc, tail))
        db.update_job(
            conn, job_id,
            status="error", percent=100,
            error="The build failed on the server. Please try again; if it "
                  "keeps failing the selection may be too large.",
            finished_at=int(time.time()))
        shutil.rmtree(build_dir, ignore_errors=True)
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def cleanup(conn):
    now = int(time.time())

    # Expire finished builds past their TTL
    rows = conn.execute(
        "SELECT id FROM jobs WHERE status = 'done' AND expires_at < ?",
        (now,)).fetchall()
    for row in rows:
        job_id = row["id"]
        shutil.rmtree(os.path.join(db.BUILDS_DIR, job_id), ignore_errors=True)
        db.update_job(conn, job_id, status="expired",
                      stage="Expired", output_name="", output_size=0)
        log("expired job %s" % job_id)

    # Orphaned build directories (job rows pruned or DB reset)
    if os.path.isdir(db.BUILDS_DIR):
        for name in os.listdir(db.BUILDS_DIR):
            job = db.get_job(conn, name)
            if job is None or job["status"] in ("expired", "error"):
                shutil.rmtree(os.path.join(db.BUILDS_DIR, name),
                              ignore_errors=True)

    # Stale scratch directories (crashed builds)
    if os.path.isdir(db.SCRATCH_DIR):
        for name in os.listdir(db.SCRATCH_DIR):
            if not name.startswith("job-"):
                continue
            path = os.path.join(db.SCRATCH_DIR, name)
            job = db.get_job(conn, name[len("job-"):])
            stale = job is None or job["status"] not in ("queued", "running")
            if stale and os.path.getmtime(path) < now - 3600:
                shutil.rmtree(path, ignore_errors=True)
                log("removed stale scratch %s" % name)

    # Decompressed base images whose release is gone
    if os.path.isdir(CACHE_DIR):
        for name in os.listdir(CACHE_DIR):
            source = os.path.join(db.RELEASES_DIR, name + ".xz")
            if name.endswith(".img") and not os.path.exists(source):
                os.unlink(os.path.join(CACHE_DIR, name))
                log("removed orphaned base cache %s" % name)

    # Prune ancient job rows
    conn.execute(
        "DELETE FROM jobs WHERE finished_at IS NOT NULL AND finished_at < ?",
        (now - 30 * 86400,))
    conn.commit()


def recover_interrupted(conn):
    """Jobs left 'running' by a worker crash/restart can never finish."""
    rows = conn.execute(
        "SELECT id FROM jobs WHERE status = 'running'").fetchall()
    for row in rows:
        db.update_job(
            conn, row["id"], status="error", percent=100,
            error="The server restarted during this build. Please try again.",
            finished_at=int(time.time()))
        log("marked interrupted job %s as failed" % row["id"])


def main():
    os.makedirs(db.SCRATCH_DIR, exist_ok=True)
    os.makedirs(db.BUILDS_DIR, exist_ok=True)
    os.makedirs(CACHE_DIR, exist_ok=True)
    conn = db.connect()

    if "--cleanup" in sys.argv:
        cleanup(conn)
        return

    log("builder worker started (root=%s)" % db.PIMAC_ROOT)
    recover_interrupted(conn)
    last_cleanup = 0.0
    while True:
        job = db.claim_next_job(conn)
        if job is not None:
            run_job(conn, job)
            continue
        if time.time() - last_cleanup > CLEANUP_INTERVAL_SECONDS:
            cleanup(conn)
            last_cleanup = time.time()
        time.sleep(POLL_SECONDS)


if __name__ == "__main__":
    main()
